from src.schemas.user import *
from src.schemas.movie import *
from src.schemas.cart import *
from src.schemas.order import *

__all__ = [
    # Auth schemas
    "UserRegister",
    "UserLogin",
    "Token",
    "TokenRefresh",
    "AccessToken",
    "PasswordChange",
    "PasswordResetRequest",
    "PasswordReset",
    "ActivationRequest",
    "UserProfileUpdate",
    "UserProfileResponse",
    "UserResponse",
    "UserGroupUpdate",
    "UserActivate",
    "Message",
    # Movie schemas
    "GenreBase",
    "GenreCreate",
    "GenreUpdate",
    "GenreResponse",
    "GenreWithCount",
    "StarBase",
    "StarCreate",
    "StarUpdate",
    "StarResponse",
    "DirectorBase",
    "DirectorCreate",
    "DirectorUpdate",
    "DirectorResponse",
    "CertificationBase",
    "CertificationCreate",
    "CertificationUpdate",
    "CertificationResponse",
    "MovieBase",
    "MovieCreate",
    "MovieUpdate",
    "MovieResponse",
    "MovieListResponse",
    "MovieLikeCreate",
    "MovieLikeResponse",
    "CommentCreate",
    "CommentUpdate",
    "CommentUserInfo",
    "CommentResponse",
    "CommentWithReplies",
    "MovieRatingCreate",
    "MovieRatingResponse",
    "MovieFavoriteResponse",
    "MovieFilters",
    "MovieSortBy",
    "PaginatedMovies",
    "PaginatedComments",
]